github:
  zip_url: https://www.dropbox.com/s/1vo4lpjfs9b52m5/lmpc-matlab-0.0.1.zip?dl=0
  tar_url: https://www.dropbox.com/s/swriqynkcm8vtpi/lmpc-matlab-0.0.1.tar.gz?dl=0

theme: jekyll-theme-minimal
