show_downloads: "true"
github:
  zip_url: https://github.com/ARMSLab/slmpc/archive/v1.0.zip
  tar_url: https://github.com/ARMSLab/slmpc/archive/v1.0.tar.gz
  repository_url: https://github.com/ARMSLab/slmpc/

title: Successive Linearization Based Model Predictive Control
description: ARMS Laboratory, <a href="http://arms.nu.edu.kz/" style="text-color: #336699;">arms.nu.edu.kz</a>

theme: jekyll-theme-cayman
