show_downloads: "true"
github:
  zip_url: https://github.com/ARMSLab/lmpc-matlab/archive/v0.1.zip
  tar_url: https://github.com/ARMSLab/lmpc-matlab/archive/v0.1.tar.gz
  github_url: https://github.com/ARMSLab/slmpc/
  
title: Successive Linearization Based Model Predictive Control

theme: jekyll-theme-cayman
